# Generated by Django 4.1.5 on 2023-02-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='total',
        ),
        migrations.AlterField(
            model_name='firm',
            name='address',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
