# Generated by Django 4.1.5 on 2023-02-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_remove_purchases_total_alter_firm_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='total',
        ),
    ]
